name: Build and Deploy

on: [push]

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install and Build 🔧
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          single-commit: true

      - name: Deploy via SCP (覆盖文件)
        uses: appleboy/scp-action@v0.1.6
        with:
          username: root
          host: ${{ secrets.SSH_IP }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: dist/
          target: /root/code/yft-admin
          overwrite: true
          rm: true